### ISSUE TITLE
Pictures are not displayed

### ISSUE THREAD

**Issue by Re1koHardeen** [JustHumanz/PixivLewdRSS#2]
The script receives images, sends them to Discord, and Discord receives them, but gives an image of poop (image error). When trying to open the image in the browser, it redirects to the site https://humanz.moe/ (yours, as I understand) to the home page

**Comment by JustHumanz** [comment]
already update the ProxyURL, can u test it?

**Comment by Re1koHardeen** [comment]
same. I think the problem is that Pixiv is blocked in my country, and since the server is local and has a local address, it doesn't want to load anything. I have no idea how to solve this problem, but it seems to be on my side

**Comment by JustHumanz** [comment]
i'm updating some code in this repo, make sure u update the code 

u can use `git pull` or just reclone this repo 


![Screenshot_2024-08-02_19-15-03](https://github.com/user-attachments/assets/59ba6305-af34-46b5-982b-d1791000389e)

**Comment by Re1koHardeen** [comment]
well, sorry, i download this update to my PC, but FORGOT patch the server :)
Thank you very much!
